language: node_js
notifications:
  email: false
cache:
  directories:
  - "$HOME/.npm"
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
jobs:
  include:
  - stage: test
    script:
    - npm run lint
    - npm run resolve-swagger-references
    - npm test
    - npm run coverage
  - stage: NPM develop release
    if: branch = develop
    script:
    - npm run resolve-swagger-references
    - npm version preminor --preid="$TRAVIS_COMMIT" --force
    deploy:
      provider: npm
      email: devops@windingtree.com
      skip_cleanup: true
      tag: develop
      api_key: "$NPM_TOKEN"
      on:
        repo: windingtree/wt-read-api
        branch: develop
  - stage: Build and publish docker image
    sudo: true
    services:
    - docker
    if: tag IS present
    script:
    - npm run resolve-swagger-references
    - docker build -t windingtree/wt-read-api:$TRAVIS_BRANCH .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push windingtree/wt-read-api:$TRAVIS_BRANCH
    - docker tag windingtree/wt-read-api:$TRAVIS_BRANCH windingtree/wt-read-api:latest
    - docker push windingtree/wt-read-api:latest
  - stage: NPM release
    if: tag IS present
    script:
    - npm run resolve-swagger-references
    - echo 'Deploying to NPM...'
    deploy:
      provider: npm
      email: devops@windingtree.com
      skip_cleanup: true
      api_key: "$NPM_TOKEN"
      on:
        repo: windingtree/wt-read-api
        tags: true
  - stage: Start service from docker with latest merged tag
    install: true
    sudo: true
    if: branch = release/playground
    script:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - npm run deploy-aws-playground
  - stage: Start service from docker with latest merged tag
    install: true
    sudo: true
    if: branch = release/lisbon
    script:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - npm run deploy-aws-lisbon
env:
  global:
  - secure: hINTP0maD3IhgnkrHmkXQEffU2kujBkaTbyHYRvYJWiAdOrKbFS+Rmgz7ZixjxHvB4zCkJkuHLRdiYcCKg1FXwFmqG7Qml5bSZYLWVt0J9n8pWGfy2UqJ5+wRkxAqtChc6LJNH/yqteM+amuTZt1Skt+ByS7l2vG4T5CjsNMJ2MTqx+gtPuGbexyurLEROWojf6HtIYT9ijodHVJQ+RReTkNgnTP/ZQGlo2Z81/lhb8BpPtAE/Bl6X7xLU8u+Z3tg847HJgWLd0XRsk9VDf9e7lr5b/J56SwGCE2NBp9btBSdakDdacl+RQ3C5DvifFd28EqVp4d7A4f6cIo/IXxL2l+5HcXF+AqfR/OL0TTCqWlAEp8auOl3oouytKtNQqHeH3xecUP6OeOyCN5dHkKvAVf5uHULe4c3/o/HQaPLYDiWFini+13e59bBP+19tIG9gESlNnoKUk27UQUwBVizeKUHHMmxXFjnsHFp387+nyNEpjPcArcvVc3YrsMZ62CCOvvNFnm8gv1b6815IcLeVYzju++iC8tf+RGX6MUe0P/1Mo/9ATjahipNOYNScX0tG1/BA610VQVzLKLjXxlXdMS4SaY9nE6IThKXOOJnmk/WFNlMJbRfq1CcKbdWFtGjwxb1fT+Yqn5S8dj3BZBna4utWIxLflCFq1LzEK02Oc=
  - secure: ZT3gTqyQQsZHFvuBTyLD3QQLAD41zCEQ7zVXrazcooj/NZ6Pvt4zyK4gFKzFYFZNZ/cCix/YIQRiZt8kIHpxUbeahyAVoov+x/Q/T0B5Ug8jZHLtJBH73T1fqwyhQt4kDkfDROrg+9XztheF+GWAXxXn+hHPR+VEVF8+Cba/SdNVoL4rP2wuP9E0/Re7+ay7OFurVPk2kRoQ7KVqgdFsr+zE9xs92Ye71TFacKPRUnlxue5cmM/UoEFD3Yecq+sMIHVGmrCfwPgdfvcFRB6nQKGG34/Dyl0xl0YFhyx3DqNBlaeYGYHjOUhZORk2Q9dpgK5cvw/ZL/dwxC+mlipQSZVCOIxc9YUYbSaRWF31iqq7UzYXRr6S/7nn6m276r/sQv8AMwuIBCvtZP9+EXd8R/2OqbRvqp4VBUbHyv+xO6lUhY2IIe8omzmAzy9E3PjyQkBKCLJPdIGrhKEZ/zT4x1BDO/kddz7NEWyxXhWbKh4bj2vCXRYX0SLATf1Bs5g10lOM2mChOqwahR2/+H03FSqSLgzqEHmbanX3yz8dfF3bwZ0mGWaVMQZk3wI345CKLeZY+HuJVXn0BL9VEhZdoHOn6/86va2hTvBXEflrIyEjbVO1gVEPwSI++WbhuUJo4CS9ND0lE6owZEq3XN/9rYw31e/8a4zWSWz6eO5POQA=
  - secure: AHvZaSot/PiBp8IUe48zs0vDNzjHPZAfkI4oX7IbrYo4Aw1BPPqTYn3bkp1byFEOwqXR8YAm4MOXhc2jk/PK+qKA6Tw8XTW1ZfarelSjUr/Rl88EfppXBzcqBfgRVFNw5SPn8gT4426lTiUtbPtOTMD3YoagGBj+xh5DKCnu83f4HlXAuu9bRqDjt3oaS4jTWJbyC9ScS+oh1Y6K5nRcf9rBerN+WT3Ttft+XKdswtNSqSvM5pKXLd+EgarMNokRC28jc1s7rzNVnzKZ3DWAFxFjjENcZljR7q66aWuGewoUsJv8801z0/rIxgZJh4nFb7BfTuit+00eXL08t7NVCwGskhiAKrlMoWg4TEsrNTm+jpC5IuaaFGz5qsDBUo6hzkDrjoDPRcOGCVQDLl2A3D/ucy4LbT+AGNOZJjbyKqDy2Zg3B31yE0FVCRT2TvH2xlxuCscwFOnTrTE7w2MeHHVdrbJzZ+C+Yn9L9Gzt3DlDT6pD7JhKXedS0b4/hWtHLerrAyskUNUiXMeE6CLBxMqzJgR7L1AoohiH1QqNjBVSl4/na9FP42W3Si0q/RjsAYCoJKI+evGemc0wL9Cx3Cnt/VA70XxqP20dX6ez5xvvKzZBFtFqmOlXPP2owz7NaRIwu56ybpZcFxAH+KfT9iw9Fj3sRsM+6kvRakgvNiw=
  - secure: epU7VYjyfgrhV8SNaZq4gjtlYP8s8yoOPfO9+Wu9ANi8V77PrNgvtfHK3IiO8ldINX2tV7Y8C8J8QFjjDjrT12apouZAgkR2B5p1V31lkdf8nuL/cmXe2ZQxjLLIYooy94/V6zxGRGBDUCVYdjDJkOZEj9OkPPiXa77KUumLPqmvAlZn2clDxFBIxeN4xJu7dBPIaj8ih1OhdEwtCxBpLWlvVLiAvCLuoOgHCFIkwB6ppO/jBYJzvg6fWNUs0I0oVt6VXJ5GgPSAJmX/U4w3bv27c5c+2f0LXsNXyy4Q8TsyO4ROAV4iPWzC8FXf/yCl9XaK1k2u3j/qa6krE4gBIssUeV/t9uwreJyzrXJw3iATjR4aA8mgyXyAtdPLCKinsRqZBeNtof7HV7RLtyH1kI3AGmaZ8hKuXRx3v6Hj8OYStRhmJyUJqbThubWSdhGIhaQlm13Q1xGtSEVIEIORcdUyEhZK2hXu0X0OQ0oIUCociZ/h5Pws0aXV9D5Dgp4sWR+1HM32L0VGgMGWUqbnsvK+lF6Tvny01JJZwJs8hdvdO32MN9N8NymEEbYMFCtF6AUIsmZD0z6oizwzxWLV+aKokSJAyxQhHQlgfcDfE36LY/V+tjaAY4Z3JaUTjaVzuyoItshV3icqWzvLyF47CJslxfA6wcyjjOogvYUCW40=
  - secure: h2P7cuys/FHC+wMx+7Lch+moIRNd4HYyfs5aiEp9Fb0kGj9u/4ilF6bqTdggZyes3hKV+g3OlkjzPPrmsVxeEWKSJT/1vgpzcFDJYDZ4j7rrj02HqSWhqjm1Yt87wk2u8a+cIt6h4DM/BQTGwNR4nXi2S2eFqV/nLM53yGyceVLyAbzAeiQ7RJQ+9zuhqVni7tjzZUm3xO0dXyiO1TLIWVN0vBPRcZCSdylrWZrcjzNj40kfdJpbOXGNwYcvuuDlD7Ug7QJKnh8uBkfOFSrfey/98FX89On1SfbsIkL8Y6sKgJMmwWWpElA5GMTYuWekhOaL6hnKsoKdHmo+jjxqLMBo6u8D1Umy/vnsJMscuPaUps3pAkSoQ3DHItj8q74cr+JAwpNp5cWoKHYbOo3Q55HmIebUheRXJt+GSgW2fNd+ubTdTs82DemNV8351avNnLxLXjgXyGiAUWTJYv+0uKyG2+J2AGbUI2Y7pYP5gQGuGhiInDIvIEm2TUwN1fJ2wtNxUvpmbIHtrtB8QBQivg8yNo0AO5op9zXns3H9ExEdiHtvhPE0GAdlTXJasU+NltgqLVD7qaBzdraH7BpthSuEZVOeYJV4zzq8K0i0CyZXRKNFS2uqBdLmKot3i4qg2XtsI6SkejvJq+HwhckyOyvbepV+6f0+2LqPJ/z1a6U=
  - secure: oDpjz0DWWNIt5A6yr9spEY/Rerge//ogrznNiJCceGr/kv6zFZ2MdJLZry71VaWZT0Rn83dGYKY0U3nETyd/NfQWBWOcOpr8ztG/WRHVdWjZo1qHnEBEfrxyQVO9xQTl3GsyhN+dLPzwU88RbNZ3aaTiXxjMjw0FAjB2E1TqQxssU0Ahqr4qxLFDKbVmdF8gHC8E3CHXorc3cEvEOfClx6rr+6VZss/DkOTjisssgarMx/wBMTf0QbOEjjzaB0r9VlCSC1lMil3zlKeN/RLFHnxEuK5JouF3UyDUI9uQo/koQ8YAEWsJRqzl4aTyTsARPS9pWANqM9d3NcD0kezHqGrzfx8oRNy0/zGgjnvn2M0ybzawDc6sfWyBm2Yol7gFV8bigNAByIFBZYzBGAuwcqBEhHRTGBpOW30xUUyt1HBuIXKG3EKs6yY93MF14J2hx0NV8aNSo5ybpZE88LH30wcUlhFmpxMX7rpmGOh6KUoEzurvvBVwEeSShCdzJExMMP808oAbBP0r1OX3j8qh7UmL3Rq9PgYdAish/jxvuXivI2nYN6R0BmLc0fSz6HGb89XQh/vR4l0PNAp29R5x773sE6GcQJ/YQc4heb95ffd1t3h0E2OkTNWl74i7+n6eB8rnblQzaqAeyhXtv1LNPK+E7MSuMhG/X/LZq8liyKI=
  - secure: N/XDIAWRn0ejWwQLYotPhi+UzGGRXnjI5LJ3s8cG2egwnBe7rYmJJUkz934LoDQr2Bh6Mjgv6w2zT4inn/aNdbRMDcFU91E0VieYe4IQk5/ODr8aZa8cXyXtAyvGKZ9N6oVjQ4tCoH5ksifGnh+vS9n2T+h4q+ghTlFJ+oixn2O0HRjaP2wENaFdhIgUEaMFQECTMt2SPSwt9HziFFlDivjT8+n/fy1tLws8G42ZhfUHWOMryfel8gDLlDS3H4A4NpCtyNlwJgdffcEaUA8C1Unk3mTcEHyq2s4T8o2v9i2LcpsSFnWkBZqkrd6OQ6HmksEYQTypMi2WU8XIWMEa9fPooxiYJpmcc8KAQwluHbggH58fk6xACgJ00fydLzlUqr413C8tzApFvTPxwpBXnTn/Wslb1abvd7SEOkyNrL4ugu0IDASVQpCU+G3j6nPf8t2FpuZUYl6BzJOQSQbHxiiluV2hD3yq+SjW+l+8wOMzH14wacOTokg4eW6u+JI87X+/PRxoZn5Vw4esrgGDnBzdQYjCFjR/3gHkYFzoyx102JAGYH21bwX+L8HS7NWljBVBhH5s1hatmWV6E+lfAEEHINNlFv7OLZVN8hu+wSweTAkT/WBO7umWZv+Vn5dQYhH7tPy1rQSjZIeDZFUPjHmgA0lezwGCFjlWHGlXfDs=
  - secure: Ft5sdwCNKPpqeVJm0eXqm1woSSfihDuPP6tqKWl5/4q/Ju09xjegFVC4yMBv86Xy5SW8wTIu/z4hdmnqZaQ/Ecd57P3Uhbt+dVCRwB40dCHdwjnOU1rh74HTgzvpuASt+1PV1mZyc+lwrWjv9yq5nfJGZ2rAH6Fke8uDVpFroPWLVhb+mkaVMYBSaQYHTWBpzbI05UKnukS6Zmwt7bKzlLNbhUWR1TKKKUHbisu9O1QwP4UtqbtOTt6+go61Zj65X08Ms6RD3+hoK9QQMGchte+OuBcHPNosemzwjFsIC+cSpiDX07ih5ai/4MZ20F2Y08qnHjurnqUGuCRqkXbhGTIL4Ss4/P3v1ZHZtaa3Jujk8GwzRsC+r8loJPeEGaB5yD2n/Z/KAkjF9Zv71Zxn4VnZSQJKmxzn42yHHqU6enZOHLAExvKfqPkXv1SKq7ZPqIHiXshCo+3Z7tEYwM+cfIOKhXMksaq30Vgk6fVkEdSXBJIkp8s9BWpa6DsAV6TkwrjbmaArqcJxRLjgO5RPirVxO8JI562FM3JOGb1LJyKXcZMCeApm7jAk11KLeTGoWWhJBYugb4sUjsx2J3Tcpl+OJviJydcn1fydyOqRJchFwOm5SloJ0XzkM/4j3VXOfjslNZK/98bdWcrjKpWyZPRT+6+PO4WZeZin9SRvGac=
